# Generated by Django 5.1.7 on 2025-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='total_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
