# Generated by Django 5.1.7 on 2025-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0002_transfer_total_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bytes_transferred', models.BigIntegerField(default=0)),
                ('total_transfers', models.IntegerField(default=0)),
            ],
        ),
    ]
